services:
  sentence-transformers:
    image: "mayank31313/mayank31313/workflow-runner:sentence-transformers"
    build:
      context: packages/workflow-runner-sentence-transformers
      dockerfile: dockerfile
    ports:
      - "8080:8000"