services:
  sentence-transformers:
    image: "mayank31313/workflow-runner:sentence-transformers"
    build:
      context: packages/workflow-runner-sentence-transformers
      dockerfile: dockerfile
  crawler:
    image: "mayank31313/workflow-runner:crawler"
    build:
      context: packages/crawler
      dockerfile: dockerfile