[project]
name = "base"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cndi>=2.4.9",
    "alembic>=1.16.4",
    "fastapi[standard]",
    "sqlmodel>=0.0.24",
    "crawl4ai",
    "pika"
]
[tool.uv.sources]
cndi = { git = "https://github.com/mayank31313/python-dependency-injection.git" }
