[project]
name = "workflow-runner-sentence-transformers"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cndi>=2.4.9",
    "cryptography>=45.0.3",
    "docker>=7.1.0",
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
    "langchain>=0.3.26",
    "langchain-elasticsearch>=0.3.2",
    "langchain-huggingface>=0.3.0",
    "langchain-ollama>=0.3.3",
    "pika>=1.3.2",
    "pydantic>=2.11.7",
    "sentence-transformers>=5.0.0",
]

[tool.uv.sources]
cndi = { git = "https://github.com/mayank31313/python-dependency-injection.git" }
