[project]
name = "workflow-runner-sentence-transformers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.16.1",
    "cndi>=2.4.9",
    "cryptography>=45.0.3",
    "docker>=7.1.0",
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
    "kubernetes>=33.1.0",
    "langchain>=0.3.26",
    "langchain-elasticsearch>=0.3.2",
    "langchain-huggingface>=0.3.0",
    "langchain-ollama>=0.3.3",
    "pika>=1.3.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "sentence-transformers>=5.0.0",
    "sqlmodel>=0.0.24",
    "transitions>=0.9.2",
]
